language: en-US

reviews:
  request_changes_workflow: true

  focus_areas:
    - "security"
    - "performance"
    - "maintainability"
    - "type_safety"

exclude_paths:
  - "node_modules/**"
  - "dist/**"
  - "build/**"
  - "*.log"
  - ".env*"
  - "vendor/**"

instructions: |
  This is a homelab dashboard project with:
  - Go backend using Fiber framework
  - Next.js 15 frontend with App Router
  - PostgreSQL database
  - JWT authentication

  Please focus on:
  - Security best practices for authentication
  - Next.js App Router conventions
  - Go error handling patterns
  - Type safety in TypeScript
  - Performance optimizations
  - Accessibility in React components