name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  backend:
    name: Backend (Go)
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16-alpine
        env:
          POSTGRES_DB: nimbus_test
          POSTGRES_USER: nimbus
          POSTGRES_PASSWORD: test_password
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Go
        uses: actions/setup-go@v6
        with:
          go-version: '1.25'
          cache-dependency-path: backend/go.sum

      - name: Install dependencies
        working-directory: ./backend
        run: |
          go mod download
          go mod verify

      - name: Run go fmt
        working-directory: ./backend
        run: |
          if [ "$(gofmt -s -l . | wc -l)" -gt 0 ]; then
            echo "Go code is not formatted:"
            gofmt -s -l .
            exit 1
          fi

      - name: Run go vet
        working-directory: ./backend
        run: go vet ./...

      - name: Run tests
        working-directory: ./backend
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: nimbus_test
          DB_USER: nimbus
          DB_PASSWORD: test_password
          JWT_SECRET: test-jwt-secret-key-for-ci-minimum-32-characters-required
          PORT: 8080
          CORS_ORIGINS: http://localhost:3000
        run: go test -v -race -coverprofile=coverage.out -covermode=atomic ./...

      - name: Build
        working-directory: ./backend
        run: go build -v -o bin/nimbus cmd/server/main.go

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./backend/coverage.out
          flags: backend
          fail_ci_if_error: false

  frontend:
    name: Frontend (Next.js)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'
          cache: 'npm'
          cache-dependency-path: frontend/package-lock.json

      - name: Install dependencies
        working-directory: ./frontend
        run: npm ci

      - name: Check formatting
        working-directory: ./frontend
        run: npm run format-check

      - name: Run linter
        working-directory: ./frontend
        run: npm run lint

      - name: Type check
        working-directory: ./frontend
        run: npx tsc --noEmit

      - name: Run tests
        working-directory: ./frontend
        env:
          JWT_SECRET: test-jwt-secret-key-for-ci-minimum-32-characters-required
        run: npm test

      - name: Build
        working-directory: ./frontend
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8080/api/v1
          JWT_SECRET: test-jwt-secret-key-for-ci-minimum-32-characters-required
        run: npm run build

      - name: Check build output
        working-directory: ./frontend
        run: |
          if [ ! -d ".next" ]; then
            echo "Build failed - .next directory not found"
            exit 1
          fi
          echo "Build successful"

      - name: Upload coverage
        uses: codecov/codecov-action@v5
        with:
          files: ./frontend/coverage/lcov.info
          flags: frontend
          fail_ci_if_error: false

  docker:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest
    needs: [backend, frontend]
    if: |
      github.ref == 'refs/heads/main' &&
      github.event_name == 'push' &&
      github.repository_owner == 'Turbootzz' &&
      needs.backend.result == 'success' &&
      needs.frontend.result == 'success'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata for backend
        id: meta-backend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nimbus-backend
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Extract metadata for frontend
        id: meta-frontend
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/nimbus-frontend
          tags: |
            type=raw,value=latest
            type=sha,prefix={{branch}}-

      - name: Build and push backend
        uses: docker/build-push-action@v6
        with:
          context: ./backend
          file: ./backend/Dockerfile
          push: true
          tags: ${{ steps.meta-backend.outputs.tags }}
          labels: ${{ steps.meta-backend.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Build and push frontend
        uses: docker/build-push-action@v6
        with:
          context: ./frontend
          file: ./frontend/Dockerfile
          push: true
          tags: ${{ steps.meta-frontend.outputs.tags }}
          labels: ${{ steps.meta-frontend.outputs.labels }}
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            NEXT_PUBLIC_APP_NAME=Nimbus

  ci-success:
    name: CI Success
    runs-on: ubuntu-latest
    needs: [backend, frontend, docker]
    if: always()
    steps:
      - name: Check all jobs
        run: |
          # Docker job is skipped on non-main branches, so treat 'skipped' as success
          docker_ok=$([[ "${{ needs.docker.result }}" == "success" ]] || [[ "${{ needs.docker.result }}" == "skipped" ]] && echo "true" || echo "false")

          if [[ "${{ needs.backend.result }}" == "success" ]] && [[ "${{ needs.frontend.result }}" == "success" ]] && [[ "$docker_ok" == "true" ]]; then
            echo "All CI jobs passed!"
            exit 0
          else
            echo "Some CI jobs failed"
            echo "Backend: ${{ needs.backend.result }}"
            echo "Frontend: ${{ needs.frontend.result }}"
            echo "Docker: ${{ needs.docker.result }}"
            exit 1
          fi
 